name: Notify on Pull Request

on:
  pull_request:
    types: [opened, edited, closed]

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.BOT_TOKEN }}
          to: ${{ secrets.CHAT_ID }}
          message: |
            Repository: ${{ github.repository }}
            Event Type: ${{ github.event_name }}
            Action: ${{ github.event.action }}
            User: ${{ github.event.sender.login }}

            Pull Request Title: ${{ github.event.pull_request.title }}
            Pull Request URL: ${{ github.event.pull_request.html_url }}
